# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.github.zouzdc.admin
  paths-to-exclude: '/error'
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
#  生产环境屏蔽
  production: true
  setting:
    language: zh_cn